# This file was generated by the {rix} R package v0.7.1 on 2024-06-05
# with following call:
# >rix(r_ver = "d125f0e4d85f1517b639d4a8f848175da46fcd3e",
#  > r_pkgs = c("tidyverse",
#  > "targets",
#  > "tarchetypes",
#  > "rmarkdown",
#  > "openxlsx",
#  > "readxl"),
#  > system_pkgs = NULL,
#  > git_pkgs = NULL,
#  > ide = "code",
#  > project_path = "~/Lab4/",
#  > overwrite = TRUE,
#  > print = TRUE)
# It uses nixpkgs' revision d125f0e4d85f1517b639d4a8f848175da46fcd3e for reproducibility purposes
# which will install R version latest.
# Report any issues to https://github.com/b-rodrigues/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/d125f0e4d85f1517b639d4a8f848175da46fcd3e.tar.gz") {};
 
 rpkgs = builtins.attrValues {
  inherit (pkgs.rPackages) 
      tidyverse
      targets
      tarchetypes
      rmarkdown
      openxlsx
      readxl
      languageserver;
 };
   
 system_packages = builtins.attrValues {
  inherit (pkgs) R glibcLocales nix;
 };
  
in

 pkgs.mkShell {
   LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then  "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
   LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

   buildInputs = [  rpkgs  system_packages  ];
   
 }
