---
title: "Maryland Labour Stike Analysis"
author: "Michael V Cumbo"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: null
---
```{r md}

dsa::motherduck_df()




```



```{r connector, include=true}
    con <- DBI::dbConnect(duckdb::duckdb(dbdir = "md:prod_lat"))
     DBI::dbSendQuery(con, paste0("USE prod_lat;"))
    test <- DBI::dbGetQuery(con, paste0("SELECT * FROM yearly_average_strike"))
    DBI::dbDisconnect(con)
    head(test)
```

```{r connector, include = true}
   con <- DBI::dbConnect(duckdb::duckdb(dbdir = "md:prod_lat"))
     DBI::dbSendQuery(con, paste0("USE prod_lat;"))
table <- DBI::dbGetQuery(con, paste0("
    WITH strikecount AS (

SELECT
DISTINCT
state,
count(*) as actualnumberofstrikes,
isoyear(startDate) as year
FROM sop
WHERE
strikeOrProtest ILIKE 'strike'
and state ILIKE 'maryland'
  GROUP BY year, state
  
  ) 
  SELECT 
  strikecount.state,
  strikecount.year,
  strikecount.actualnumberofstrikes,
  medianstrike.yearly_median_strikes,
  CASE WHEN
  strikecount.actualnumberofstrikes < medianstrike.yearly_median_strikes
  THEN 'Below Median Strikes'
  WHEN strikecount.actualnumberofstrikes > medianstrike.yearly_median_strikes
  THEN 'Above Median Strikes'
  WHEN strikecount.actualnumberofstrikes = medianstrike.yearly_median_strikes
  THEN 'Equal to Median Strikes' 
  End as MedianStrikes
  FROM strikecount
  LEFT JOIN yearly_average_strike as medianstrike
  ON medianstrike.isoyear = strikecount.year
  ORDER BY strikecount.year ASC
  ;
  "))
    DBI::dbDisconnect(con)
    
    print(table)


```




```{r national_numbers, include = TRUE }






```